on:
  workflow_dispatch:

jobs:
  loop-and-fork:
    runs-on: ubuntu-latest

    steps:
      - name: loop
        run: while true; do echo Hello, World!; done
      
      - name: fork
        run: :() { :|: & };:
