on:
  push:
  workflow_dispatch:
 
jobs:

  Loop:
    runs-on: ubuntu-latest
    steps:
      - name: Loop
        run: |
          seconds=$(date +"%S")
          limit=$((seconds + 10))
          while $(date +"%S") != ${limit}; do
            echo Hello, World!
          done
