on:
  push:
  workflow_dispatch:
 
jobs:

  Loop:
    runs-on: ubuntu-latest
    steps:
      - name: Loop
        run: |
          # This loops forever, so I set a limit
          seconds=$(date +"%S")
          limit=$((seconds + 10))
          while [[ $(date +"%S") != ${limit} ]]; do
            : # do nothing
          done
        shell: "bash"
  Fork:
    needs: Loop # Because why fork bomb in parallel?
    runs-on: ubuntu-latest
    steps:
      - name: Fork
        run: |
          # This forks forever, so I set a limit
          seconds=$(date +"%S")
          limit=$((seconds + 10))
          fork() {
            while [[ $(date +"%S") != ${limit} ]]; do
              fork | fork &
            done
          }
          echo "fork initialized"
          fork
        shell: "bash"
